 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/media", type: :request do
  # Medium. As you add validations to Medium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Medium.create! valid_attributes
      get media_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      medium = Medium.create! valid_attributes
      get medium_url(medium)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_medium_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      medium = Medium.create! valid_attributes
      get edit_medium_url(medium)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Medium" do
        expect {
          post media_url, params: { medium: valid_attributes }
        }.to change(Medium, :count).by(1)
      end

      it "redirects to the created medium" do
        post media_url, params: { medium: valid_attributes }
        expect(response).to redirect_to(medium_url(Medium.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Medium" do
        expect {
          post media_url, params: { medium: invalid_attributes }
        }.to change(Medium, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post media_url, params: { medium: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested medium" do
        medium = Medium.create! valid_attributes
        patch medium_url(medium), params: { medium: new_attributes }
        medium.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the medium" do
        medium = Medium.create! valid_attributes
        patch medium_url(medium), params: { medium: new_attributes }
        medium.reload
        expect(response).to redirect_to(medium_url(medium))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        medium = Medium.create! valid_attributes
        patch medium_url(medium), params: { medium: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested medium" do
      medium = Medium.create! valid_attributes
      expect {
        delete medium_url(medium)
      }.to change(Medium, :count).by(-1)
    end

    it "redirects to the media list" do
      medium = Medium.create! valid_attributes
      delete medium_url(medium)
      expect(response).to redirect_to(media_url)
    end
  end
end
